fixing compiling errors
Build FAILED.

       "D:\a\pos\pos\PosSystem.sln" (default target) (1) ->
       "D:\a\pos\pos\PosSystem.App\PosSystem.App.csproj" (default target) (5) ->
       "D:\a\pos\pos\PosSystem.App\PosSystem.App_akmwkhmm_wpftmp.csproj" (_CompileTemporaryAssembly target) (6) ->
       (CoreCompile target) ->
         D:\a\pos\pos\PosSystem.App\App.xaml.cs(68,18): error CS0234: The type or namespace name 'Licensing' does not exist in the namespace 'PosSystem.Core' (are you missing an assembly reference?) [D:\a\pos\pos\PosSystem.App\PosSystem.App_akmwkhmm_wpftmp.csproj]
         D:\a\pos\pos\PosSystem.App\App.xaml.cs(69,17): error CS0234: The type or namespace name 'Licensing' does not exist in the namespace 'PosSystem.Core' (are you missing an assembly reference?) [D:\a\pos\pos\PosSystem.App\PosSystem.App_akmwkhmm_wpftmp.csproj]